### PR TITLE
add autogroup:internet, fix reduce filter rules

### LINKED ISSUE #1786: Reducing filter rules breaks exit node access
## Bug description

When setting up an ACL to allow access to a exit node, the access rules can be reduced because the ips defined are not in use by the network or routes. 

## Environment

- OS: N/A
- Headscale version:
- Tailscale version: N/A

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## Logs and attachments

Trying to create the following setup:
- user1-user3 are part of the group "team"
- user "internal" contains internal services/servers
- "internal" should not be able to access anything
- "team" should be able to access all of "internal"
- "team" members should be able to access all own devices but not other users
- "internal" contains multiple exit nodes

If I just use the following ACL, the "team" members are able to successfully access all "internal" devices. However when trying to use a exit node inside "internal" it is not possible to ping/access any devices outside the tailscale network.

``` { "action": "accept", "src": ["group:team"], "dst": ["internal:*"] },```

```
{
  "groups": {
    "group:team": ["user3", "user2", "user1"]
  },
  "acls": [
    { "action": "accept", "src": ["group:team"], "dst": ["internal:*"] },
    {
      "action": "accept",
      "src": ["group:team"],
      "dst": [ "0.0.0.0/5:*",
               "8.0.0.0/7:*",
               "11.0.0.0/8:*",
               "12.0.0.0/6:*",
               "16.0.0.0/4:*",
               "32.0.0.0/3:*",
               "64.0.0.0/2:*",
               "128.0.0.0/3:*",
               "160.0.0.0/5:*",
               "168.0.0.0/6:*",
               "172.0.0.0/12:*",
               "172.32.0.0/11:*",
               "172.64.0.0/10:*",
               "172.128.0.0/9:*",
               "173.0.0.0/8:*",
               "174.0.0.0/7:*",
               "176.0.0.0/4:*",
               "192.0.0.0/9:*",
               "192.128.0.0/11:*",
               "192.160.0.0/13:*",
               "192.169.0.0/16:*",
               "192.170.0.0/15:*",
               "192.172.0.0/14:*",
               "192.176.0.0/12:*",
               "192.192.0.0/10:*",
               "193.0.0.0/8:*",
               "194.0.0.0/7:*",
               "196.0.0.0/6:*",
               "200.0.0.0/5:*",
               "208.0.0.0/4:*"
              ]
    },
    { "action": "accept", "src": ["user3"], "dst": ["user3:*"] },
    { "action": "accept", "src": ["user2"], "dst": ["user2:*"] },
    { "action": "accept", "src": ["user1"], "dst": ["user1:*"] }
  ]
}
```

### LINKED ISSUE #1817: headscale 0.23.0-alpha5 ignores /32 masks in ACLs
## Bug description

We have tailnet network with node1 as subnet router to `172.16.0.0/24` network.

After updating to 0.23.0-alpha5 some of our users lost access to resources provided by ACL. Here short example of acl.yaml:

```
groups:
  group:access:
    - user1
hosts:
  net.vlan0: 172.16.0.0/24
  net.dns01: 172.16.0.21/32
# ...
acls:
  - action: accept
    src:
      - group:access
    dst:
      - tag:access-servers:* # node1 in it
      - net.dns01:*
```

Users in group `access` (user1) now cannot access to 172.16.0.21. If I change `net.dns01` with `net.vlan0` in ACL, user1 can ping 
172.16.0.21 (and other addresses in 172.16.0/24 too which is undesirable). Previous version 0.22.3 was allowed access to hosts with /32 mask.

## Environment

- OS: Linux
- Headscale version: 0.23.0-alpha5
- Tailscale version: 1.56, 1.60

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## To Reproduce

Have subnet router and ACLs to networks behind it.

## Logs and attachments

netmap with acl /32 in config:

```
...
                {
                        "SrcIPs": [
                                "100.64.0.3/32",
                                "fd7a:115c:a1e0::b/128"
                        ]
                        "DstPorts": [
                                {
                                        "IP": "100.64.0.2/32",
                                        "Bits": null,
                                        "Ports": {
                                                "First": 0,
                                                "Last": 65535
                                        }
                                },
                                {
                                        "IP": "fd7a:115c:a1e0::2/128",
                                        "Bits": null,
                                        "Ports": {
                                                "First": 0,
                                                "Last": 65535
                                        }
                                },
                        ]
                 }
```

netmap with acl /24 in config:

```
...
                {
                        "SrcIPs": [
                                "100.64.0.3/32",
                                "fd7a:115c:a1e0::b/128"
                        ]
                        "DstPorts": [
                                {
                                        "IP": "100.64.0.2/32",
                                        "Bits": null,
                                        "Ports": {
                                                "First": 0,
                                                "Last": 65535
                                        }
                                },
                                {
                                        "IP": "fd7a:115c:a1e0::2/128",
                                        "Bits": null,
                                        "Ports": {
                                                "First": 0,
                                                "Last": 65535
                                        }
                                },
                                {
                                        "IP": "172.16.0.0/24",
                                        "Bits": null,
                                        "Ports": {
                                                "First": 0,
                                                "Last": 65535
                                        }
                                }
                        ]
                 }
```

### PR DESCRIPTION
**Pull request by kradalby**
This PR contains two features: 

- `autogroup:internet` for policy
- fix of a too aggressive reduction of node specific rules

The majority of lines in this PR is tests based on #1817 and #1786.

Fixes #1817
Fixes #1786
Updates #657

### CODE REVIEW

**Review by juanfont — APPROVED** [review]

File: hscontrol/policy/acls.go [hunk 1]
```diff
@@ -36,6 +36,38 @@ const (
...
+	// Delete Private network addresses
+	// https://datatracker.ietf.org/doc/html/rfc1918
+	internetBuilder.RemovePrefix(netip.MustParsePrefix("fc00::/7"))
+	internetBuilder.RemovePrefix(netip.MustParsePrefix("10.0.0.0/8"))
+	internetBuilder.RemovePrefix(netip.MustParsePrefix("172.16.0.0/12"))
+	internetBuilder.RemovePrefix(netip.MustParsePrefix("192.168.0.0/16"))
+
+	// Delete Tailscale networks
+	internetBuilder.RemovePrefix(netip.MustParsePrefix("fd7a:115c:a1e0::/48"))
+	internetBuilder.RemovePrefix(netip.MustParsePrefix("100.64.0.0/10"))
```
Comment (Gurkengewuerz) [inline hscontrol/policy/acls.go:61]: Since you can define custom ip prefixes is it a good practice to assume the user is using the default tailscale network?

Comment (kradalby) [reply hscontrol/policy/acls.go:61]: The tailscale client does not support other up ranges, so while it is configurable in Headscale you cannot use anything else.

If that changes we could read it from the config.
Happy to take a pr changing it to the config values if you are up for it :)

Comment (Gurkengewuerz) [reply hscontrol/policy/acls.go:61]: thanks to make it clear. didn't knew that and just read through the code and commented with my thoughts. 😁
