### PR TITLE
cli: only validate bypass-grpc set policy

### LINKED ISSUE #2825: [Bug] v0.27.0 policy apply errors
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Multiple errors during policy apply
```
2025-10-27T13:10:04Z TRC ../home/runner/work/headscale/headscale/hscontrol/policy/v2/filter.go:37 > resolving source ips error="multiple errors:\n\tuser with token \"user@\" not found\n\tuser with token \"user1@\" ... "
```
As far as I understand, this error is displayed separately for each group and with list of all users in group.

Users:
```
root@ip-10-255-1-11:/home/u# headscale users list
ID | Name     | Username.   | Email                     | Created
1  | user     | user        | user@example.com          | 2025-07-29 10:46:19
2  | user1    | user1       | user1@example.com         | 2025-07-29 10:54:18
...
```

Policy:
```
  "groups": {
    "group:example": [
      "user@",
      "user1@"
]
...
```

### Expected Behavior

`headscale policy set -f policy.json`

### Steps To Reproduce

1. apply policy

### Environment

```markdown
- OS: CLI MacOS, Server Linux
- Headscale version: 0.27.0
- Tailscale version:
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

```
2025-10-27T13:10:04Z TRC ../home/runner/work/headscale/headscale/hscontrol/policy/v2/filter.go:37 > resolving source ips error="multiple errors:\n\tuser with token \"user@\" not found\n\tuser with token \"user1@\" ... "

2025-10-27T15:31:31+02:00 DBG Policy filter hash changed filter.hash.new=73d84082 filter.hash.old=00000000 filter.rules=0 filter.rules.new=1
2025-10-27T15:31:31+02:00 DBG Tag owner hash changed tagOwner.hash.new=35dcc9c4 tagOwner.hash.old=00000000 tagOwners.new=7 tagOwners.old=0
2025-10-27T15:31:31+02:00 DBG Auto-approvers hash changed autoApprove.hash.new=ac2bfb0f autoApprove.hash.old=00000000 autoApprovers.new=1 autoApprovers.old=0
2025-10-27T15:31:31+02:00 DBG Exit node set hash changed exitSet.hash.new=43a78ec8 exitSet.hash.old=00000000
2025-10-27T15:31:31+02:00 DBG Policy changes require node updates autoApprovers.changed=true exitNodes.changed=true filter.changed=true tagOwners.changed=true
Policy updated.
```

### PR DESCRIPTION
**Pull request by kradalby**
When adding the mode to bypass gRPC, a naive policy validation was added to both the gRPC set, and the bypass mode.

This caused the policy to invalidate in unexpected ways as the gRPC already handles this validation in the backend.

This commit moves the validation logic into the bypass branch.

Fixes #2825

### CODE REVIEW

File: cmd/headscale/cli/policy.go [hunk 1]
```diff
@@ -159,6 +153,17 @@ var setPolicy = &cobra.Command{
 				ErrorOutput(err, fmt.Sprintf("Failed to open database: %s", err), output)
 			}
 
+			users, err := d.ListUsers()
+			if err != nil {
+				ErrorOutput(err, fmt.Sprintf("Failed to load users fro policy validation: %s", err), output)
```
Comment (nblock) [inline cmd/headscale/cli/policy.go]: typo: `for`
