### PR TITLE
policy/v2: accept RFC 3986 bracketed IPv6 in ACL destinations

### LINKED ISSUE #2754: [Bug] Headscale does not accept IPv6 addresses with brackets
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The following ACL is accepted by Tailscale SaaS:

```json
{
	"acls": [
		{
			"action": "accept",
			"src":    ["alice@"],
			"dst":    ["[fd7a:115c:a1e0::87e1]:80,443"]
		}
	]
}
```

Headscale 0.26.1 refuses to load this ACL, error:

```
FTL ../runner/work/headscale/headscale/cmd/headscale/cli/serve.go:24 > Error initializing error="creating new headscale: loading ACL policy: creating policy manager: parsing policy: parsing policy from bytes: Invalid alias \"[fd7a:115c:a1e0::87e1]\". An alias must be one of the following types:\n- wildcard (*)\n- user (containing an \"@\")\n- group (starting with \"group:\")\n- tag (starting with \"tag:\")\n- autogroup (starting with \"autogroup:\")\n- host\n\nPlease check the format and try again."
```

As a workaround, rewrite as: 

- `"fd7a:115c:a1e0::87e1:80,443"` or 
- `"fd7a:115c:a1e0::87e1/128:80,443"`

### Expected Behavior

It should accept 

### Steps To Reproduce

1. Setup Headscale 0.26.1 with the above policy (v2)

### Environment

```markdown
- OS: Debian 13
- Headscale version: 0.26.1
- Tailscale version: -
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

not required.

### PR DESCRIPTION
**Pull request by kradalby**
Headscale rejects IPv6 addresses with square brackets in ACL policy
destinations (e.g. `[fd7a:115c:a1e0::87e1]:80,443`), while Tailscale
SaaS accepts them.

The root cause is that `splitDestinationAndPort` uses
`strings.LastIndex(":")` which leaves brackets on the destination
string, and `netip.ParseAddr` does not accept brackets.

Add a bracket-handling branch at the top of `splitDestinationAndPort`
that uses `net.SplitHostPort` for RFC 3986 parsing when input starts
with `[`. The extracted host is validated with
`netip.ParseAddr`/`ParsePrefix` to ensure brackets are only accepted
around IP addresses and CIDR prefixes, not hostnames or other alias
types like tags and groups.

Fixes #2754

claude-opus-4 was used in this PR.

### CODE REVIEW

File: hscontrol/policy/v2/types_test.go [hunk 1]
```diff
@@ -1766,6 +1766,191 @@ func TestUnmarshalPolicy(t *testing.T) {
...
+			},
+		},
+		{
+			name: "2754-bracketed-ipv4",
+			input: `
+{
+	"acls": [{
+		"action": "accept",
+		"src": ["alice@"],
+		"dst": ["[192.168.1.1]:80"]
```
Comment (nblock) [inline hscontrol/policy/v2/types_test.go:1936]: I've never seen bracketed IPv4?
