### PR TITLE
policy: reject unsupported fields

### LINKED ISSUE #2626: [Bug] ACL invalid policy accepted
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Running policy check with invalid src/dst returns "Policy is valid"

### Expected Behavior

Policy check fails and returns an error.

### Steps To Reproduce

1) Create `acls.jsonc` policy using the configuration below
2) Run policy check against bad `acls.jsonc` file: `headscale policy check -f ./acls.jsonc`
3) Returns `Policy is valid`

```jsonc
{
    "acls": [
        { "action": "accept", "BAD": ["FOO:BAR:FOO:BAR"], "BAD": ["BAD:BAD:BAD:BAD"] }
      ]
}
```

### Environment

```markdown
- OS: Fedora CoreOS 42.20250427.3.0
- Headscale version: v0.26.0
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

```jsonc
{
    "acls": [
        { "action": "accept", "BAD": ["FOO:BAR:FOO:BAR"], "BAD": ["BAD:BAD:BAD:BAD"] }
      ]
}
```

### PR DESCRIPTION
**Pull request by kradalby**
This PR switches to using the new jsonv2 package in go making it easier for us to reject unsupported fields in the policy, fixing #2626.

It adds an exception to allow fields starting with `#` in ACL rules to allow metadata used by headscale-admin (cc @GoodiesHQ). 

It also introduces some stricter types for `Action` and `Protocol` making it part of the strict parsing format and not a "runtime" check. 

In addition it cleans up a bit of unused variables.

Fixes #2626

### CODE REVIEW

**Comment by GoodiesHQ** [comment]
Awesome! Thanks for thinking of headscale-admin :)

**Comment by kradalby** [comment]
Please give it a go, it only allows them in `acls` atm

File: hscontrol/policy/v2/types.go [hunk 1]
```diff
@@ -1237,13 +1242,277 @@ func resolveAutoApprovers(p *Policy, users types.Users, nodes views.Slice[types.
...
+	ProtocolEGP      Protocol = "egp"
+	ProtocolIGP      Protocol = "igp"
+	ProtocolUDP      Protocol = "udp"
+	ProtocolGRE      Protocol = "gre"
+	ProtocolESP      Protocol = "esp"
+	ProtocolAH       Protocol = "ah"
+	ProtocolIPv6ICMP Protocol = "ipv6-icmp"
+	ProtocolSCTP     Protocol = "sctp"
+	ProtocolFC       Protocol = "fc"
+	ProtocolWildcard Protocol = "*"
```
Comment (nblock) [inline hscontrol/policy/v2/types.go:1352]: Tailscale does not allow a wildcard `*` as value for the proto field - error message: `Error: proto name "*" not known; use protocol number 0-255`

File: hscontrol/policy/v2/types.go [hunk 2]
```diff
@@ -1237,13 +1242,277 @@ func resolveAutoApprovers(p *Policy, users types.Users, nodes views.Slice[types.
...
+// MarshalJSON implements JSON marshaling for SSHAction.
+func (a SSHAction) MarshalJSON() ([]byte, error) {
+	return json.Marshal(string(a))
+}
+
+// Protocol represents a network protocol with its IANA number and descriptions.
+type Protocol string
+
+const (
+	ProtocolICMP     Protocol = "icmp"
```
Comment (nblock) [inline hscontrol/policy/v2/types.go:1338]: Tailscale ignores the case for names. It accepts any case (e.g. `icmp`, `IcmP`, `ICMP`, …) while Headscale only allows the lowercase variant: `icmp`

File: hscontrol/policy/v2/types.go [hunk 3]
```diff
@@ -1237,13 +1242,277 @@ func resolveAutoApprovers(p *Policy, users types.Users, nodes views.Slice[types.
...
+	case ProtocolAH:
+		return []int{protocolAH}, true
+	case ProtocolSCTP:
+		return []int{protocolSCTP}, false
+	case ProtocolICMP:
+		return []int{protocolICMP, protocolIPv6ICMP}, true
+	default:
+		// Try to parse as a numeric protocol number
+		// This should not fail since validation happened during unmarshaling
+		protocolNumber, _ := strconv.Atoi(string(p))
```
Comment (nblock) [inline hscontrol/policy/v2/types.go:1431]: `0` is an invalid protocol number - Tailscale error message: `Error: leading 0 not permitted in protocol number "0"`. Headscale currently accepts `0`.
