### PR TITLE
all: add HA subnet router health probing

### LINKED ISSUE #2129: [Bug] online status doesn't change if connection is interrupted
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the connection of a client is interrupted (pull the cable, disconnect from wifi) headscale never changes its status to offline.
The state changes to offline when I restart headscale or caddy. (which terminates all connections)

### Expected Behavior

The node should go offline after some time.

### Steps To Reproduce

Connect a device and inerrupt it's internet connection.

### Environment

```markdown
- OS: Flatcar Linux
- Headscale version: v0.23.0-beta.5
- Tailscale version: 1.72.1

I tested it with an Android Phone and my Linux machine. (Ubuntu 22.04)
The reverse proxy is Caddy with one line standard configuration reverse proxy setup. Headscale runs in a Docker container with sqlite DB.
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

### Anything else?

I can provide further logs and dumps if this problem does not appear in another setup.

### LINKED ISSUE #2902: Implement tailcfg.PingRequest
Implement [`tailcfg.PingRequest`](https://github.com/tailscale/tailscale/blob/9048ea25db8064b3833b7a2fcbe4b421e4a820dc/tailcfg/tailcfg.go#L1844).

PingRequests allows the control server (Headscale) to send special requests to the client and get a response.

They can be range from simple "are you alive" requests to "asking the client to report back something" ([c2n requests](https://github.com/tailscale/tailscale/blob/main/tailcfg/c2ntypes.go)). 

This is needed to fix the following:
- https://github.com/juanfont/headscale/issues/1850 (c2n and internal endpoints)
- https://github.com/juanfont/headscale/issues/2129 (ping client to understand if it down)

### PR DESCRIPTION
**Pull request by kradalby**
Periodically ping HA subnet routers via the Noise control channel and fail over to a healthy standby when the primary stops responding. This catches "zombie connected" nodes that hold their control session open but cannot forward traffic — the existing disconnect-based failover never fires because the Noise session is still alive.

Enabled by default (probe_interval: 10s, probe_timeout: 5s). Only active when HA routes exist (2+ nodes advertising the same prefix). Set node.routes.ha.probe_interval to 0 to disable. A node that recovers is marked healthy but does not reclaim primary to avoid flapping.

Fixes #2129
Fixes #2902

Generated with the help of an AI assistant

### CODE REVIEW

File: hscontrol/state/ha_health.go [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+	ctx context.Context,
+	dispatch func(...change.Change),
+) {
+	haNodes := p.state.primaryRoutes.HANodes()
+	if len(haNodes) == 0 {
+		return
+	}
+
+	// Deduplicate node IDs across prefixes.
+	seen := make(map[types.NodeID]struct{})
```
Comment (kradalby) [inline hscontrol/state/ha_health.go]: This could be the tailscale set.Set type

File: hscontrol/state/ha_health.go [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+		pingID, responseCh := p.state.RegisterPing(id)
+		callbackURL := p.serverURL + "/machine/ping-response?id=" + pingID
+
+		dispatch(change.PingNode(id, &tailcfg.PingRequest{
+			URL: callbackURL,
+		}))
+
+		wg.Add(1)
+
+		go func(nodeID types.NodeID, pID string, ch <-chan time.Duration) {
```
Comment (kradalby) [inline hscontrol/state/ha_health.go]: Use the new wg.Go function

File: hscontrol/state/state.go [hunk 3]
```diff
@@ -1184,6 +1188,11 @@ func (s *State) RoutesForPeer(
 	return reduced
 }
 
+// PrimaryRoutes returns the primary routes tracker.
+func (s *State) PrimaryRoutes() *routes.PrimaryRoutes {
+	return s.primaryRoutes
+}
```
Comment (kradalby) [inline hscontrol/state/state.go:1194]: Why is this exported? Cant see it being used?

Comment (kradalby) [reply hscontrol/state/state.go:1194]: Only `hscontrol/servertest/ha_health_test.go` uses this — 7 call sites assert or flip health state to drive failover tests. Options:

(a) keep exported for test observability
(b) replace with focused `State.IsNodeHealthy(nodeID)` / `State.SetNodeHealthy(nodeID, bool)` helpers — hides internal `primaryRoutes` structure, narrower test surface

Prefer (b) unless you want to keep the broader accessor for future debug tooling.

File: hscontrol/state/ha_health.go (hunk 1 above)
Comment (kradalby) [reply hscontrol/state/ha_health.go]: Done — fixed up into 5e68d469.

File: hscontrol/state/ha_health.go (hunk 2 above)
Comment (kradalby) [reply hscontrol/state/ha_health.go]: Done — fixed up into 5e68d469.

**Review by juanfont — APPROVED** [review]

**Comment by gawsoftpl** [comment]
How this ha works I reeived 

I have two routes
```
ID  | Hostname                    | Approved      | Available     | Serving (Primary)      
423 | cluster-production-worker-0 | 10.100.1.0/30 | 10.100.1.0/30 | 10.100.1.0/30          
424 | cluster-production-worker-1 | 10.100.1.0/30 | 10.100.1.0/30 |                  
```

But in logs I get warnings
```
headscale  | 2026-06-02T10:06:51Z INF http request bytes=19 elapsed=0.01039 method=HEAD path=//machine/ping-response proto=HTTP/1.1 remote=172.18.0.4:33188 status=404
headscale  | 2026-06-02T10:06:51Z INF http request bytes=19 elapsed=0.012342 method=HEAD path=//machine/ping-response proto=HTTP/1.1 remote=172.18.0.4:33194 status=404
headscale  | 2026-06-02T10:06:56Z WRN HA probe: node did not respond node.id=423 timeout=5000
headscale  | 2026-06-02T10:06:56Z WRN HA probe: node did not respond node.id=424 timeout=5000
headscale  | 2026-06-02T10:07:01Z INF http request bytes=19 elapsed=0.033657 method=HEAD path=//machine/ping-response proto=HTTP/1.1 remote=172.18.0.4:36678 status=404
headscale  | 2026-06-02T10:07:01Z INF http request bytes=19 elapsed=0.013928 method=HEAD path=//machine/ping-response proto=HTTP/1.1 remote=172.18.0.4:36692 status=404
headscale  | 2026-06-02T10:07:06Z WRN HA probe: node did not respond node.id=424 timeout=5000
headscale  | 2026-06-02T10:07:06Z WRN HA probe: node did not respond node.id=423 timeout=5000
```
Both nodes is working and response but HA dont works. This endpoint `/machine/ping-response` are implemented in tailscale client ?

Path `//machine/ping-response` looks like there was no http url server "//" should be `endpoint/machine/ping-response` ?

**Comment by kradalby** [comment]
Could you open an issue please? I’m not going to be able to keep track of comments on closed issues and prs

**Comment by gawsoftpl** [comment]
> Could you open an issue please? I’m not going to be able to keep track of comments on closed issues and prs

Problem resolved. All works.
I had a problem in config

In my config was: `https://myheadscale.example.com/`
should be: `https://myheadscale.example.com:443`
