### PR TITLE
policy: More testing, some bug fixes

### LINKED ISSUE #3157: [Bug] missing routes for subnet to subnet traffic
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

We have a subnet-router-a that advertises subnet_a and a subnet-router-b that advertises subnet_b. Both subnet routers have --accept-routes=true and --snat-subnet-routes=false set

When we have a acl rule that only allows traffic between subnet-a and subnet-b it does not create routes on the subnet routes. E.g the cidr for subnet_a is missing in the route table 52 of subnet-router-b, so no traffic is routed for this subnets.

```
"acls": [
               {
               	// Allow subnet_a to subnet_b
               	"action": "accept",
               	"src": [
               		"subnet_a"
               	],
               	"dst": [
               		"subnet_b:*"
               	]
               }
],
 "hosts": {
                "subnet_a": "10.88.8.0/24",
                "subnet_b": "10.99.9.0/24"
}
```

I know it is intended to reduce the routes to only have those permitted by the acl. But this case is missing in the "CanAccessRoute" function in node.go, as it only checks for matches "node.IPs to route" and not  "node.SubnetRoutes to routes"

a workaround is to add the subnet routers to the source and destination until this is fixed

### Expected Behavior

Necessary routes are created when there is an acl for subnet to subnet traffic.

(With talescale.com as controller this acl rule works as intended / routes are created)

### Steps To Reproduce

1.  Create two subnet router and advertise their local subnet.
2. Approve the advertised routes in headscale
3. create a acl rule that only allows subnet_a to subnet_b but not subnet router to subnet
4. check routes on subnet router (ip route show table 52) --> route to subnet on other subnet router is missing

### Environment

```markdown
Headscale:
- OS: Ubuntu 24.04 LTS (and 22.04 LTS in test)
- Headscale version: 0.28.0
- Nr. of Clients: 155
Client:
- OS: OpenWRT 24.10.4 (in prod) and Ubuntu 24.04 (in test)
- Tailscale version: 1.80.3 and 1.96.2
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

This function does not check for matching node.SubnetRoutes() as described above
https://github.com/juanfont/headscale/blob/97fa117c48a58bee3941e5e8b4393873501afe14/hscontrol/types/node.go#L324-L338

### LINKED ISSUE #3169: [Bug] Exit node not visible / routes trafic with acl and autogroup:internet
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Exit node is not visible when acl configured:
```
{
  "acls": [   
    {
      "action": "accept",
      "src": ["*"],
      "dst": ["autogroup:internet:*"]
    }
  ]
}
```

Exit node is registered for user `gateway`, user is `user`. Without acl configured, node is visible and internet is reachable via node.

```
{
  "groups": {
    "group:gateway": ["gateway@"]
  },
  "acls": [
    {
      "action": "accept",
      "src": ["*"],
      "dst": ["group:gateway:*"]
    },
    {
      "action": "accept",
      "src": ["*"],
      "dst": ["autogroup:internet:*"]
    }
  ]
}
```
With that acl, exit node becomes visible and ping-able, but internet is not reachable via exit node.

```
{
  "acls": [
    {
      "action": "accept",
      "src": ["*"],
      "dst": ["group:gateway:*"]
    },
    {
      "action": "accept",
      "src": ["*"],
      "dst": ["autogroup:internet:*"]
    },
    {
      "action": "accept",
      "src": ["*"],
      "dst": ["0.0.0.0/0:*"]
    }
  ]
}
```

Only with allow of `0.0.0.0/0:*` internet via exit node becomes reachable.

### Expected Behavior

Exit node is visible and forwards trafic with documented allow rule:
```
{
  "action": "accept",
  "src": ["*"],
  "dst": ["autogroup:internet:*"]
}
```

### Steps To Reproduce

1. Setup headscale
2. Add exit node with user `gateway`
3. Add client with another user `user`
4. Check exit node reachability and internet via exit node
5. Configure ACL
6. Check again

### Environment

```markdown
- OS:Ubuntu 22.04
- Headscale version:v0.0.0-20260401131042-835db974b5cd
- Tailscale 1.82.4 on Android
- Tailscale 1.96.4 on Linux (Ubuntu)
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

Root Cause
Two bugs in the policy compilation pipeline:
1. hscontrol/policy/v2/filter.go — autogroup:internet skipped entirely
compileNetPortRanges() had a continue for autogroup:internet with a comment
saying it is handled via AllowedIPs/exit node routing.

No FilterRule entries were generated for internet ranges
matcher.MatchesFromFilterRules() produced empty matchers
CanAccess() could not determine exit node visibility via DestsIsTheInternet()
Clients received an empty PacketFilter and dropped all internet-bound traffic locally

2. hscontrol/policy/policyutil/reduce.go — rules stripped from exit node's filter
Even if explicit internet CIDR rules existed, ReduceFilterRules() stripped them
from the exit node's PacketFilter because any CIDR overlapping 0.0.0.0/0
(an exit route) was unconditionally skipped:

With current fix, ACL works fine: https://github.com/max-mal/headscale/commit/061ba42bfe3f8b001309515bcefb38b9beb9df0c

[exit_node_netmap_patched.json](https://github.com/user-attachments/files/26476581/exit_node_netmap_patched.json)
[exit_node_netmap.json](https://github.com/user-attachments/files/26476582/exit_node_netmap.json)

### PR DESCRIPTION
**Pull request by kradalby**
This PR addresses a series of issues, some marked as fixed. In addition it brings in a significant amount of test data from some runs with a testing tool.

Any reviewer should ignore the first commit as its mostly json blobs.

Fixes #3157
Fixes #3169

Generated with the help of an AI assistant

### CODE REVIEW

File: hscontrol/types/node.go [hunk 1]
```diff
@@ -40,11 +40,18 @@ var (
 type RouteFunc func(id NodeID) []netip.Prefix
 
 // ViaRouteResult describes via grant effects for a viewer-peer pair.
+// Invariant: UsePrimary ⊆ Include.
```
Comment (kradalby) [inline hscontrol/types/node.go]: Is is an incredibly unhelpful comment.

**Review by juanfont — APPROVED** [review]
