### PR TITLE
hscontrol: enforce that tagged nodes never have user_id

### LINKED ISSUE #3077: Migrating to tagged devices leaves user_id set
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I just updated from 0.27.1 to 0.28.0 and assigned tags to several devices which lead to migration to "tagged-devices". As there was no device left for legacy-user1 and legacy-user2 (not linked to oidc), i tried to delete them. CLI gives error `Cannot destroy user: user not empty: node(s) found` because in the database the tagged devices are still in relation with the corresponding user_id.

Image

I then tried to reassign the tag with `headscale nodes tag -2 -t tag:name` but the user_id persists and the legacy users cannot be deleted.

### Expected Behavior

Legacy users that are migrated to tagged-devices can be deleted without an error message.

### Steps To Reproduce

Create user and assign devices, then add tag to migrate these users. Try to delete existing user without node assgned.

### Environment

```markdown
- OS: Debian 13
- Headscale version: 0.28.0
- Tailscale version: 1.90.4
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

-

### PR DESCRIPTION
**Pull request by kradalby**
Tagged nodes are owned by their tags, not a user. Enforce this by setting `user_id = NULL` on tagged nodes — both via a migration for existing data and at every write path going forward.

This makes `DestroyUser` work naturally since tagged nodes no longer reference any user.

Fixes #3077

claude-opus-4 was used in this PR.

### CODE REVIEW

File: hscontrol/state/state.go [hunk 1]
```diff
@@ -1871,17 +1873,20 @@ func (s *State) HandleNodeFromPreAuthKey(
 
 		// For user-owned keys, check if node exists for a different user
 		// For tags-only keys (pak.User == nil), this check is skipped
-		if pak.User != nil && existsAnyUser && existingNodeAnyUser.Valid() && existingNodeAnyUser.UserID().Get() != pak.User.ID {
-			// Node exists but belongs to a different user
-			// Create a NEW node for the new user (do not transfer)
-			// This allows the same machine to have separate node identities per user
-			oldUser := existingNodeAnyUser.User()
+		if pak.User != nil && existsAnyUser && existingNodeAnyUser.Valid() && !existingNodeAnyUser.IsTagged() && existingNodeAnyUser.UserID().Get() != pak.User.ID {
```
Comment (kradalby) [inline hscontrol/state/state.go]: This is a really gnarly if statement that is very hard to read, can we break it down?
