### PR TITLE
cli: add --id flag to API key expire/delete commands

### LINKED ISSUE #2986: [Bug] unable to expire apikeys
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi all,

I'm trying to expire some apikeys I've created, but when I try I get the following error

**Headscale API Error

There was an error communicating with the Headscale API.
The server responded with a status code of 500, indicating a server-side issue. Please check the Headscale server status and try again later.

{
  "code": 2,
  "message": "failed to parse auth-key: key too short, expected at least 77 chars after prefix, got 16",
  "details": []
}**

and I'm not able to delete the apikey.
Could anyone help me to understand what is happening?
tnx

### Expected Behavior

delete the created apikeys

### Steps To Reproduce

1. access to the Settings/ Pre-Auth Keys page
2. try to delete any key

### Environment

```markdown
Here is my configuration:
headplane running in a docker:
ghcr.io/tale/headplane:0.6.2-beta.3
# headscale version 
headscale version v0.28.0-beta.1
commit: 7be20912f5861ef9d6fa42a615e44e6c0b0f2c17
build time: 2025-12-18T11:42:32Z
built with: go1.25.1 linux/amd64
# uname -a
Linux esterno 6.12.57+deb13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.57-1 (2025-11-05) x86_64 GNU/Linux
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 13 (trixie)"
NAME="Debian GNU/Linux"
VERSION_ID="13"
VERSION="13 (trixie)"
VERSION_CODENAME=trixie
DEBIAN_VERSION_FULL=13.2
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

[netmap.json](https://github.com/user-attachments/files/24383114/netmap.json)

[status.json](https://github.com/user-attachments/files/24383120/status.json)

### PR DESCRIPTION
**Pull request by kradalby**
Adds `--id` flag as alternative to `--prefix` for API key expire/delete operations.

Fixes #2986

## Usage
```bash
headscale apikeys expire --id <id>
headscale apikeys delete --id <id>
```

### CODE REVIEW

File: hscontrol/db/api_key_test.go [hunk 1]
```diff
@@ -36,6 +36,27 @@ func (*Suite) TestAPIKeyDoesNotExist(c *check.C) {
 	c.Assert(key, check.IsNil)
 }
 
+func (*Suite) TestGetAPIKeyByID(c *check.C) {
```
Comment (kradalby) [inline hscontrol/db/api_key_test.go]: use testify, not old check.

File: hscontrol/grpcv1.go [hunk 2]
```diff
@@ -604,7 +604,14 @@ func (api headscaleV1APIServer) ExpireApiKey(
...
 	var err error
 
-	apiKey, err = api.h.state.GetAPIKey(request.Prefix)
+	if request.GetId() != 0 {
+		apiKey, err = api.h.state.GetAPIKeyByID(request.GetId())
+	} else if request.GetPrefix() != "" {
+		apiKey, err = api.h.state.GetAPIKey(request.GetPrefix())
+	} else {
+		return nil, status.Error(codes.InvalidArgument, "must provide id or prefix")
+	}
```
Comment (kradalby) [inline hscontrol/grpcv1.go]: should this be a helper?
