### PR TITLE
state: allow untagging nodes via reauth with empty RequestTags

### LINKED ISSUE #2979: [Bug] Reauth to untag a device keeps it tagged
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

SaaS allows to untag a node by reauth with an empty list of tags. This removes all tags from a node and assigns ownership back to the user. See [Tailscale docs](https://tailscale.com/kb/1068/tags#apply-a-tag-to-a-device-with-the-cli) for a description and limitations.

This does not work in Headscale:

```bash
# regular
tailscale up --login-server https://headscale.example.com --advertise-tags=

# or forced
tailscale up --login-server https://headscale.example.com --advertise-tags= --force-reauth
```

After reauth, the node is still assigned to `tagged-devices` and keeps its previous list of tags:

```bash
$ headscale nodes list -t
ID | Hostname | Name | MachineKey | NodeKey | User           | IP addresses                  | Ephemeral | Last seen           | Expiration | Connected | Expired | ForcedTags | InvalidTags | ValidTags
1  | n2       | n2   | [0x2Hd]    | [W2y+g] | tagged-devices | 100.64.0.1, fd7a:115c:a1e0::1 | false     | 2025-12-21 11:54:34 | N/A        | online    | no      | tag:bar    |             |          
   |          |      |            |         |                |                               |           |                     |            |           |         | tag:foo    |             |          
```

### Expected Behavior

After reauth with an empty list of tags, the node should be assigned back to the user that performed the reauth and should have all of its tags removed.

### Steps To Reproduce

1. Start with a tagged node
2. Reauth: `tailscale up --login-server https://headscale.example.com --advertise-tags=`
3. Observe `headscale nodes list -t`

### Environment

```markdown
- OS: Debian 13
- Headscale version: 0.28.0-beta.1
- Tailscale version: 1.92.3
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

none

### PR DESCRIPTION
**Pull request by kradalby**
When a node re-authenticates via OIDC/web auth with empty RequestTags
(from `tailscale up --advertise-tags= --force-reauth`), remove all tags
and return ownership to the authenticating user.

This allows nodes to transition from any tagged state (including nodes
originally registered with a tagged pre-auth key) back to user-owned.

Fixes #2979

### CODE REVIEW

File: hscontrol/state/state.go [hunk 1]
```diff
@@ -1316,12 +1317,130 @@ func (s *State) HandleNodeFromAuthPath(
...
+				Caller().
+				Uint64("node.id", uint64(node.ID)).
+				Str("node.name", node.Hostname).
+				Strs("request.tags", requestTags).
+				Strs("current.tags", node.Tags).
+				Bool("is.tagged", node.IsTagged()).
+				Bool("was.authkey.tagged", wasAuthKeyTagged).
+				Msg("Processing RequestTags during reauth")
+
+			// Case 1: Empty/nil RequestTags = untag node
```
Comment (kradalby) [inline hscontrol/state/state.go]: I dont like the comment style of "case 1, case 2".

File: hscontrol/state/state.go [hunk 2]
```diff
@@ -1316,12 +1317,130 @@ func (s *State) HandleNodeFromAuthPath(
 			} else {
 				node.Expiry = regEntry.Node.Expiry
 			}
+
+			// Process RequestTags during reauth (Issue #2979)
```
Comment (kradalby) [inline hscontrol/state/state.go]: This whole code sections is adding a lot more code to an already long and complicated function.

Can some of this checking logic be factored out into a separate function?
The logging is good and important, but it is quite space consuming, can the logger be built as variables and reused to make subsequent log calls shorter?

File: hscontrol/state/state.go [hunk 3]
```diff
@@ -1316,12 +1317,130 @@ func (s *State) HandleNodeFromAuthPath(
...
+				}
+			}
 		})
 
 		if !ok {
 			return types.NodeView{}, change.Change{}, fmt.Errorf("%w: %d", ErrNodeNotInNodeStore, existingNodeSameUser.ID())
 		}
 
+		// Check if reauth was rejected due to unauthorized tags
+		if regEntry.Node.Hostinfo != nil && regEntry.Node.Hostinfo.RequestTags != nil && len(regEntry.Node.Hostinfo.RequestTags) > 0 {
```
Comment (kradalby) [inline hscontrol/state/state.go]: complicated ifs should have a named variable explaining the check.

**Review by nblock — DISMISSED** [review]
I could not get this to work. When forcing a reauth with an empty list of tags: `tailscale up --login-server=... --advertise-tags= --force-reauth`, the device keeps its tags and is still assigned to `tagged-devices`. 

Headscale sees the node as "offline".


Debug logs from the server when reauth is forced on the node:
```
DBG hscontrol/mapper/batcher_lockfree.go:572 > Successfully removed connection chan=0xc000441c70 node.id=1 remaining_connections=0
DBG hscontrol/mapper/batcher_lockfree.go:138 > Node disconnected from batcher because all connections removed, keeping entry for rapid reconnection node.id=1
DBG received register request with no auth, and no existing node machine.key=[YFV7U] node.key=[XtJ1c] unexpected=true
INF Starting node registration using key: ftndU4nCOjXeHpTi2pMbweRE
DBG received register request with no auth, and no existing node machine.key=[YFV7U] node.key=[XtJ1c] unexpected=true
DBG hscontrol/state/state.go:1299 > Updating existing node registration node.id=1 node.name=n1 registrationMethod=cli registration_id=ftndU4nCOjXeHpTi2pMbweRE user.name=alice
DBG hscontrol/state/maprequest.go:28 > using NetInfo from previous Hostinfo in MapRequest node.id=1 preferredDERP=4
DBG hscontrol/state/state.go:1671 > Policy manager user update initiated because user list modification detected user.count=1
DBG hscontrol/state/state.go:1678 > Policy manager user update completed because SetUsers operation finished policy.changed=true
INF Node registered successfully hostname=n1 node_id=1 registration_key=hskey-reg-cOTQhVkSy9-GxAY3hm20xyNSZ8GEi__fkMMz_z9FPe9kzeThU9jtCvKLMWV2pryk
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason="policy change"
DBG hscontrol/mapper/batcher_lockfree.go:609 > send: skipping send to node with no active connections (likely rapid reconnection) node.id=1
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason=
DBG hscontrol/state/maprequest.go:28 > using NetInfo from previous Hostinfo in MapRequest node.id=1 preferredDERP=4
DBG hscontrol/state/maprequest.go:28 > using NetInfo from previous Hostinfo in MapRequest node.id=1 preferredDERP=4
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason="endpoint/DERP update"
DBG hscontrol/mapper/batcher_lockfree.go:609 > send: skipping send to node with no active connections (likely rapid reconnection) node.id=1
INF Node disconnected node.id=1 node.name=n1
INF Node connected node.id=1 node.name=n1
DBG hscontrol/routes/primary.go:157 > PrimaryRoutes.SetRoutes called node.id=1 prefixes=[]
DBG hscontrol/routes/primary.go:49 > updatePrimaryLocked starting
DBG hscontrol/routes/primary.go:140 > updatePrimaryLocked completed changed=false finalState="Available routes:\n\n\nCurrent primary routes:\n"
DBG hscontrol/routes/primary.go:175 > SetRoutes completed (remove) changed=false newState="Available routes:\n\n\nCurrent primary routes:\n" node.id=1 wasPresent=false
INF hscontrol/poll.go:332 > node has connected, mapSession: 0xc0008b4160, chan: 0xc00027b3b0 node.id=1 node.name=n1 omitPeers=false stream=true
DBG hscontrol/mapper/batcher_lockfree.go:549 > addConnection: waiting for mutex - POTENTIAL CONTENTION POINT chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 node.id=1
DBG hscontrol/mapper/batcher_lockfree.go:557 > Successfully added connection after mutex wait chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 mutex_wait_time=0.054994 node.id=1 total_connections=1
DBG hscontrol/mapper/batcher_lockfree.go:103 > Node connection established in batcher because AddNode completed successfully active.connections=1 node.id=1 total.duration=0.335249
DBG hscontrol/poll.go:220 > AddNode succeeded in poll session because node added to batcher node.id=1 node.name=n1
DBG hscontrol/routes/primary.go:157 > PrimaryRoutes.SetRoutes called node.id=1 prefixes=[]
DBG hscontrol/routes/primary.go:49 > updatePrimaryLocked starting
DBG hscontrol/routes/primary.go:140 > updatePrimaryLocked completed changed=false finalState="Available routes:\n\n\nCurrent primary routes:\n"
DBG hscontrol/routes/primary.go:175 > SetRoutes completed (remove) changed=false newState="Available routes:\n\n\nCurrent primary routes:\n" node.id=1 wasPresent=false
INF hscontrol/poll.go:332 > node has disconnected, mapSession: 0xc0001a49a0, chan: 0xc000441c70 node.id=1 node.name=n1 omitPeers=false stream=true
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason="node added"
DBG hscontrol/mapper/batcher_lockfree.go:614 > send: broadcasting to all connections node.id=1 total_connections=1
DBG hscontrol/mapper/batcher_lockfree.go:624 > send: attempting to send to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG hscontrol/mapper/batcher_lockfree.go:637 > send: successfully sent to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG send: completed broadcast failed_connections=0 node.id=1 remaining_connections=1 successful_sends=1
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason="node online"
DBG hscontrol/mapper/batcher_lockfree.go:614 > send: broadcasting to all connections node.id=1 total_connections=1
DBG hscontrol/mapper/batcher_lockfree.go:624 > send: attempting to send to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG hscontrol/mapper/batcher_lockfree.go:637 > send: successfully sent to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG send: completed broadcast failed_connections=0 node.id=1 remaining_connections=1 successful_sends=1
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason="node offline"
DBG hscontrol/mapper/batcher_lockfree.go:614 > send: broadcasting to all connections node.id=1 total_connections=1
DBG hscontrol/mapper/batcher_lockfree.go:624 > send: attempting to send to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG hscontrol/mapper/batcher_lockfree.go:637 > send: successfully sent to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG send: completed broadcast failed_connections=0 node.id=1 remaining_connections=1 successful_sends=1
DBG hscontrol/mapper/batcher.go:143 > Node change processing started because change notification received node.id=1 reason="node added"
DBG hscontrol/mapper/batcher_lockfree.go:614 > send: broadcasting to all connections node.id=1 total_connections=1
DBG hscontrol/mapper/batcher_lockfree.go:624 > send: attempting to send to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG hscontrol/mapper/batcher_lockfree.go:637 > send: successfully sent to connection chan=0xc00027b3b0 conn.id=03a7ebf9856f96e6 connection_index=0 node.id=1
DBG send: completed broadcast failed_connections=0 node.id=1 remaining_connections=1 successful_sends=1
```

**Review by nblock — APPROVED** [review]
