### PR TITLE
state: preserve nil expiry on user owned registration when no default is configured

### LINKED ISSUE #3198: [Bug] User owned re registration with zero expiry stores 0001-01-01 instead of NULL
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When a user owned node registers or re registers with a pre auth key, if the client does not send an expiry AND `node.expiry` is configured as `0` (no default), the `nodes.expiry` column gets `0001-01-01 00:00:00` (Go zero time) instead of NULL.

### Expected Behavior

The column should be NULL, matching the behaviour for tagged nodes and the value consumers use to distinguish "no expiry" from "expired at year 1". The headplane "no expiry" badge is an example of a consumer that checks `=== null`.

### Steps To Reproduce

1. Configure `node.expiry: 0` in headscale
2. `headscale preauthkeys create` for a user
3. Register a node with that key (client sends zero expiry by default)
4. `sqlite3 db.sqlite "SELECT id, hostname, expiry FROM nodes"` shows `0001-01-01 00:00:00` for that node
5. Expected: NULL

### Environment

```markdown
- OS: Linux
- Headscale version: current master (after 6337a3db)
- Tailscale version: any
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

Root cause is in `hscontrol/state/state.go`. Two sites build a non nil pointer to `regReq.Expiry` regardless of whether the value is zero time:

- Line 2132 (re registration with same MachineKey): `node.Expiry = &regReq.Expiry`
- Line 2231 (initial registration): `Expiry: &regReq.Expiry` passed to `createAndSaveNewNode`

Both were introduced in commit 6337a3db (fix for #3111). The `needsDefaultExpiry` guard at `state.go:1644` checks `.IsZero()` but only applies a default when `s.cfg.Node.Expiry > 0`, so when both the request and the config are zero the pointer to zero time survives to the database.

A regression test and fix are in an accompanying PR.

### PR DESCRIPTION
**Pull request by akhilesharora**
- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [x] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [x] updated CHANGELOG.md

When a user owned node registers or re registers with a PreAuthKey and the client sends zero expiry while `node.expiry` is set to `0`, the node's `expiry` column ends up as `0001-01-01 00:00:00` instead of NULL. `hscontrol/state/state.go` builds a pointer to `regReq.Expiry` unconditionally at two sites, even when the value is zero time. Downstream consumers that distinguish "no expiry" from "expired at year 1" (the headplane "no expiry" badge checks `=== null`) see the wrong state.

This change converts an unset `regReq.Expiry` to nil before handing it off, so the `needsDefaultExpiry` guard at `state.go:1644` is the only place that assigns a non nil pointer.

Added a regression test `TestReregistrationZeroExpiryStaysNil` that covers both initial and re registration paths with `node.expiry=0` and zero client expiry. It fails on master and passes with this change. Full `go test ./hscontrol/...` passes.

This is a narrower sibling of #3170 (tagged node on tailscaled restart) on the user owned PreAuthKey path. The regression was introduced alongside the fix for #3111 in commit 6337a3db.

Fixes #3198

### CODE REVIEW

File: hscontrol/state/state.go [hunk 1]
```diff
@@ -2216,6 +2218,15 @@ func (s *State) HandleNodeFromPreAuthKey(
 			pakUser = *pak.User
 		}
 
+		// Only pass the client-requested expiry when it is actually set.
+		// A pointer to a zero time.Time gets persisted as "0001-01-01 00:00:00"
+		// rather than NULL, which breaks downstream consumers that distinguish
+		// "no expiry" from "expires at year 1".
+		var reqExpiry *time.Time
```
Comment (kradalby) [inline hscontrol/state/state.go:2225]: From Claude:

```
Same `!IsZero → &x; else → nil` shape shows up twice now — here and in the re-registration `else` branch above. Not worth a helper for two sites, but if a third appears, a small `expiryOrNil(t time.Time) *time.Time` would read nicer than the branch. Fine as-is for now.
```

File: hscontrol/auth_tags_test.go [hunk 2]
```diff
@@ -1119,3 +1119,67 @@ func TestReregistrationAppliesDefaultExpiry(t *testing.T) {
...
 		"re-registration expiry should be later than initial registration expiry")
 }
+
+// TestReregistrationZeroExpiryStaysNil tests that when a user-owned node
+// re-registers with zero client expiry and node.expiry is disabled (0),
+// the node's expiry stays nil rather than being set to a pointer to zero
+// time. Regression test for the else branch introduced in commit 6337a3db
+// which assigned `&regReq.Expiry` (pointer to time.Time{}) instead of nil,
+// causing the database row to hold `0001-01-01 00:00:00` instead of NULL.
+func TestReregistrationZeroExpiryStaysNil(t *testing.T) {
```
Comment (kradalby) [inline hscontrol/auth_tags_test.go:1129]: From Claude:

```
Test covers the user-owned path nicely. The initial-registration fix at `state.go:2218` also handles the tags-only PreAuthKey case (tagged node → `Expiry=nil`), but that isn't exercised here. The `!regReq.Expiry.IsZero()` gate at the call site makes it obvious by inspection, so not blocking — but a comment noting that the same fix covers the tagged path would help a future reader.
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -108,6 +108,7 @@ connected" routers that maintain their control session but cannot route packets.
 - Policy validation error messages now include field context (e.g., `src=`, `dst=`) and are more descriptive [#2180](https://github.com/juanfont/headscale/pull/2180)
 - Remove old migrations for the debian package [#3185](https://github.com/juanfont/headscale/pull/3185)
 - Install `config-example.yaml` as example for the debian package [#3186](https://github.com/juanfont/headscale/pull/3186)
+- **Node Expiry**: Fix user owned re registration with zero client expiry and no default storing `0001-01-01 00:00:00` in the database instead of NULL [#3199](https://github.com/juanfont/headscale/pull/3199)
```
Comment (kradalby) [inline CHANGELOG.md:111]: From Claude:

```
Pre-existing rows already holding `0001-01-01 00:00:00` aren't backfilled by this change — they keep the bad value until the node re-registers, at which point the fix naturally corrects them. If that turns out to be annoying for users with long-lived nodes, a one-shot `UPDATE nodes SET expiry = NULL WHERE expiry < '1900-01-01'` migration is cheap to add. Worth a line in the CHANGELOG or a followup issue noting this.
```

**Review by kradalby — APPROVED** [review]
Looks good, I think we should merge this, I did a little Claude review as well and got back a couple of things.

File: hscontrol/auth_tags_test.go (hunk 2 above)
Comment (akhilesharora) [reply hscontrol/auth_tags_test.go:1134]: Fixed in [4ab88296](https://github.com/juanfont/headscale/pull/3199/changes/4ab88296a9c5026cabd7f6cfb625cc2a02541000)

File: CHANGELOG.md (hunk 3 above)
Comment (akhilesharora) [reply CHANGELOG.md:111]: Fixed in [4ab88296](https://github.com/juanfont/headscale/pull/3199/changes/4ab88296a9c5026cabd7f6cfb625cc2a02541000)

**Comment by akhilesharora** [comment]
> Looks good, I think we should merge this, I did a little Claude review as well and got back a couple of things.

Thanks! Pushed 4ab88296 with the test comment and changelog line

**Comment by kradalby** [comment]
looks good, there is a lint failure, and I think it needs a rebase of main too.

**Comment by akhilesharora** [comment]
> looks good, there is a lint failure, and I think it needs a rebase of main too.

Rebased!
