### PR TITLE
Use Prometheus duration parser 

### LINKED ISSUE #322: Unable to set expiration time for preauth key in days
**Bug description**

Unable to set expiration time when creating preauth key in days, operation fails with the following message:

`invalid argument "365d" for "-e, --expiration" flag: time: unknown unit "d" in duration "365d"`

**To Reproduce**

`headscale preauthkeys create -e 365d -n example-ns` or any other number

**Context info**
Version of headscale used: v0.12.4

### PR DESCRIPTION
**Pull request by kradalby**
Use the duration parser from the Prometheus project, this allows us to use `d`, `w` and `y`.

This fixes #322

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [x] added unit tests
- [x] added integration tests
- [x] updated documentation if needed
- [x] updated CHANGELOG.md

### CODE REVIEW

File: cmd/headscale/cli/preauthkeys.go [hunk 1]
```diff
@@ -6,14 +6,15 @@ import (
...
+	"github.com/prometheus/common/model"
 	"github.com/pterm/pterm"
 	"github.com/rs/zerolog/log"
 	"github.com/spf13/cobra"
 	"google.golang.org/protobuf/types/known/timestamppb"
 )
 
 const (
-	DefaultPreAuthKeyExpiry = 1 * time.Hour
+	DefaultPreAuthKeyExpiry = "1h"
```
Comment (juanfont) [inline cmd/headscale/cli/preauthkeys.go:17]: Ew.

**Review by juanfont — APPROVED** [review]
