### PR TITLE
#2140 Fixed reflection of hostname change

### LINKED ISSUE #2140: [Bug] Hostname changes are not reflected
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing the hostname of a node is not reflected on headscale.

Using `tailscale set --hostname hello` still keeps the hostname that the node originally came with.

### Expected Behavior

Changing the hostname of a node on the node itself should reflect it on the node list in headscale.
This is the current behavior with 0.22.3.

### Steps To Reproduce

1. Start 0.23.0 (either upgraded from 0.22.3 or a fresh install)
2. Register a new node on the server
3. Note its hostname
4. Change the hostname. On desktop, `tailscale set --hostname something`. On mobile, it is located in the settings of the app.
5. Note that the hostname stayed the same

### Environment

```markdown
- OS: Docker 27.0.3 (Host: Debian 12.6)
- Headscale version: 0.23.0
- Tailscale version: 1.74.1 (ccd6bf2f4ee6421c23789b64e6e63c2ccbe87e08)
- Tailscale version (phone): iOS 18.0 // TS 1.74.0 (TestFlight beta 101.74.0)
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hopleus**
- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [x] added unit tests
- [x] added integration tests
- [ ] updated documentation if needed
- [x] updated CHANGELOG.md

Fixes #2140

### CODE REVIEW

File: hscontrol/types/node.go [hunk 1]
```diff
@@ -97,6 +97,11 @@ type (
 	Nodes []*Node
 )
 
+// IsAutomaticNameMode returns whether the `givenName` can be automatically changed based on the `Hostname` of the node.
+func (node *Node) IsAutomaticNameMode() bool {
```
Comment (kradalby) [inline hscontrol/types/node.go:101]: I find this name quite confusing, maybe something like "GivenNameHasBeenChanged"?

Comment (hopleus) [reply hscontrol/types/node.go:101]: > I find this name quite confusing, maybe something like "GivenNameHasBeenChanged"?

It's not bad. I'll fix it now

**Review by kradalby — APPROVED** [review]

**Comment by kradalby** [comment]
Thank you! your help is much appreciated, I'm a bit overloaded at the moment, so I try to come to it as I have some spare moments.
