### PR TITLE
fix(routes): ensure routes are correctly propagated

### LINKED ISSUE #1075: Routes are not propagated in v0.18.0-beta1
Hello,

**Bug description**

It seems routes are not correctly propagated when enabling or disabling them through the CLI.
Encountered that while trying https://github.com/juanfont/headscale/pull/1024

**To Reproduce**

Advertise the same route from multiple nodes (to test HA failover). Enable or disable these routes.
Route does not appear in "ip route show table 52". It appears only if I restart tailscale on the node.

**Context info**

Headscale version: v0.18.0-beta1
Tailscale version: v1.34.1
OS: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by fatih-acar**
When using Tailscale v1.34.1, enabling or disabling a route does not effectively add or remove the route from the node's routing table. We must restart tailscale on the node to have a netmap update.

Fix this by refreshing last state change so that a netmap diff is sent.

Also do not include secondary routes in allowedIPs, otherwise secondary routes might be used by nodes instead of the primary route.

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

Fixes #1075

### CODE REVIEW

File: routes.go [hunk 1]
```diff
@@ -309,6 +309,7 @@ func (h *Headscale) handlePrimarySubnetFailover() error {
 		}
 	}
 
+	h.setLastStateChangeToNow()
```
Comment (juanfont) [inline routes.go:312]: This should only run if subnets were actually failed over.

File: machine.go [hunk 2]
```diff
@@ -675,19 +675,14 @@ func (h *Headscale) toNode(
...
 		addrs...) // we append the node own IP, as it is required by the clients
 
-	enabledRoutes, err := h.GetEnabledRoutes(&machine)
-	if err != nil {
-		return nil, err
-	}
-
-	allowedIPs = append(allowedIPs, enabledRoutes...)
-
 	primaryRoutes, err := h.getMachinePrimaryRoutes(&machine)
```
Comment (juanfont) [inline machine.go:678]: > Also do not include secondary routes in allowedIPs, otherwise secondary routes might be used by nodes instead of the primary route.

I reckon that is not correct. Primary routes handled by that node are specified in the dedicated 
`PrimaryRoutes` field of `tailcfg.Node` https://github.com/juanfont/headscale/blob/main/machine.go#L741, even if we are including _all_ the enabled routes in `AllowedIPs`.

File: machine.go [hunk 3]
```diff
@@ -1057,6 +1052,7 @@ func (h *Headscale) EnableRoutes(machine *Machine, routeStrs ...string) error {
 		}
 	}
 
+	h.setLastStateChangeToNow()
```
Comment (juanfont) [inline machine.go:1055]: This looks good.

**Review by juanfont — COMMENTED** [review]
Thanks for spotting it. 

Added some comments.

File: routes.go (hunk 1 above)
Comment (fatih-acar) [reply routes.go]: Should be fixed.

File: machine.go (hunk 2 above)
Comment (fatih-acar) [reply machine.go:678]: This is what I assumed first after reading the structure's documentation. It states
```
// PrimaryRoutes are the routes from AllowedIPs that this node
// is currently the primary subnet router for, as determined
// by the control plane. It does not include the self address
// values from Addresses that are in AllowedIPs.
PrimaryRoutes []netip.Prefix `json:",omitempty"`
```

But it seems this field is used as an informative one so that subnet routers know that they are the primary router of an HA route. It is not used to populate the routing table of other peers... `AllowedIPs` is used for that.
I don't know Tailscale's internals as much as you, so I will let you double-check.

**Comment by juanfont** [comment]
You have a very good point! Otherwise old clients (pre-subnet HA) would not work...

File: routes.go (hunk 1 above)
Comment (juanfont) [reply routes.go]: Thanks!

**Comment by juanfont** [comment]
thanks!!
