### PR TITLE
types: avoid NodeView clone in CanAccess

### LINKED ISSUE #3108: [Bug] Performance regression after upgrade 0.26.1 to 0.27.1
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After upgrading Headscale from 0.26.1 to 0.27.1, CPU usage jumped under the same workload (~80 connected clients, same config/policy). Overall CPU usage went from ~5% to ~60% even when nothing really happened (no active reconnects, etc).

Upgrading to 0.28.0 did not help.

### Expected Behavior

Upgrading from 0.26.1 to 0.27.1 should not cause this CPU/memory regression under the same traffic pattern. The changelog says performance _should_ improve after introducing in-memory state in 0.27.x, but it got worse.

### Steps To Reproduce

1. Run Headscale 0.27.1 with ~80 connected clients.
2. Let normal traffic run.
3. Capture profiles:
    - `go tool pprof "http://localhost:9090/debug/pprof/profile?seconds=30"`
    - `go tool pprof "http://localhost:9090/debug/pprof/allocs?seconds=30"` (profile.MemProfileAllocs needs to be enabled)
5. Inspect:
    - `go tool pprof -http=localhost:8080 <path-to-cpu-profile>`
    - `go tool pprof -http=localhost:8080 <path-to-mem-profile>`

### Environment

```markdown
- OS: Ubuntu 24.04, Kernel 6.8
- Headscale version: 0.27.1
– Go: 1.26.0
- Tailscale version: 1.94.2
- Number of nodes: ~80 connected
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

I profiled this and attached CPU + heap allocation flamegraphs.

CPU:
Image

Memory allocation space:
Image

The hotspot is:
```
BuildPeerMap -> NodeView.CanAccess -> NodeView.AsStruct -> Node.Clone / Hostinfo.Clone / NetInfo.Clone / maps.clone
```

This path allocates about **2.31GB in 30 seconds**.

### PR DESCRIPTION
**Pull request by dmeremyanin**
NodeView.CanAccess called node2.AsStruct() on every check. In peer-map construction we run CanAccess in O(n^2) pair scans (often twice per pair), so that per-call clone multiplied into large heap churn.

This PR removes that clone path in `CanAccess` and keeps the same behavior.

I also added a simple benchmark. Local results:
```
❯ go test ./hscontrol/types -run '^$' -bench BenchmarkNodeViewCanAccess -benchmem
goos: darwin
goarch: arm64
pkg: github.com/juanfont/headscale/hscontrol/types
cpu: Apple M4 Pro
BenchmarkNodeViewCanAccess/pointer-14           26586536                45.93 ns/op           48 B/op          2 allocs/op
BenchmarkNodeViewCanAccess/struct_clone-14        513435              2254 ns/op           14944 B/op         10 allocs/op
PASS
ok      github.com/juanfont/headscale/hscontrol/types   2.590s
```

So it's roughly 50x faster in this benchmark, with much lower allocations.

Fixes #3108

---

- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [x] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

File: hscontrol/types/node.go [hunk 1]
```diff
@@ -800,11 +800,11 @@ func (nv NodeView) InIPSet(set *netipx.IPSet) bool {
 }
 
 func (nv NodeView) CanAccess(matchers []matcher.Match, node2 NodeView) bool {
-	if !nv.Valid() {
+	if !nv.Valid() || !node2.Valid() {
 		return false
 	}
 
-	return nv.ж.CanAccess(matchers, node2.AsStruct())
+	return nv.ж.CanAccess(matchers, node2.ж)
```
Comment (kradalby) [inline hscontrol/types/node.go:807]: I agree, this looks like an oversight and it would be fine to use the internal here. Good catch.

Comment (dmeremyanin) [reply hscontrol/types/node.go:807]: Great, thanks for confirming. Does the PR look good to merge as-is, or would you like any changes first? Also, should I add a changelog entry for this, and do you want to keep the benchmark test or drop it before merge?

Comment (kradalby) [reply hscontrol/types/node.go:807]: You can leave them, this is fine.

**Comment by dmeremyanin** [comment]
I'm not sure the CI failure is related to the changes in this PR

**Review by kradalby — APPROVED** [review]

**Comment by dmeremyanin** [comment]
@kradalby thanks for merging!

I've been playing around with a few more performance improvements, and in my setup CPU usage is basically close to zero now. I know you're usually pretty careful about performance-related changes in Headscale, but would you be open to reviewing a couple more PRs like this in the future? No new libraries or major core logic changes involved.

**Comment by Cediddi** [comment]
@dmeremyanin; As a user of Headscale, I'd be more than happy if you'd contribute your performance-related PRs. 🙏  Thanks for this PR
