### PR TITLE
hscontrol: rewrite hostname logic to match Tailscale SaaS

### LINKED ISSUE #363: MagicDNS doesn't register hostnames with upper-case letters
**Bug description**

Machines are not added to MagicDNS if their hostname contains capital letters. 

**To Reproduce**

1. Set hostname on client system to something with capital letters e.g. Foo-Bar. 
2. Enroll with Headscale server using `tailscale up --login-server <URL> --auth-key <AUTH_KEY>`
3. Try to ping the client system from another client using Foo-Bar or Foo-Bar.<namespace>.<baseurl>
OR run `nslookup Foo-Bar`
4. Receive failures on both commands
5. Re-connect to the Headscale server and manually set hostname to lower-case letters using `tailscale up --hostname=foo-bar --login-server <URL>`
6. Ping and nslookup are both able to find the system at foo-bar.

**Context info**

- Headscale version: 14.0
- Tailscale client: 1.22
- Server OS: Ubuntu 20.04
- Client OS: Ubuntu 20.04

Let me know if this is a known issue or if anyone else can reproduce it. I have limited systems to test on.

Thank you!

### LINKED ISSUE #2121: [Bug] Different A record for nodes with the same name
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While testing https://github.com/juanfont/headscale/issues/1369#issuecomment-2339901185, I noticed the following behavior:

#### Setup
* Node with name `laptop` assigned to user `alice` : 100.64.0.2, fd7a:115c:a1e0::2
* Node with name `laptop` assigned to user `bob`:  100.64.0.3, fd7a:115c:a1e0::3
* Config:
  ```yaml
  dns:
    use_username_in_magic_dns: false
    base_domain: tn.example.com
  ```
* Content of `/etc/resolv.conf` on both nodes:
  ```
  nameserver 100.100.100.100
  search tn.example.com
  ```

#### On alice's node
```bash
alice:~$ tailscale ip
100.64.0.2
fd7a:115c:a1e0::2

alice:~$ dig +short laptop.tn.example.com
100.64.0.3
```

#### On bob's node
```bash
bob:~$ tailscale ip
100.64.0.3
fd7a:115c:a1e0::3

bob:~$ dig +short laptop.tn.example.com
100.64.0.2
```

You get a different IP depending on depending on **where** you ask. Interestingly, Tailscale resolves to the IP of the *other* node.

### Expected Behavior

Not sure which IP address, but I'd expect to always get the same one.

### Steps To Reproduce

* Create two users
* Register a node for each user (using unique names, e.g. `laptop` for user `alice` and `server` for user `bob`)
* Run: `headscale nodes rename -i ID_OF_SERVER_BOB laptop`
* Node list:
```
$ headscale nodes list
ID | Hostname  | Name      | MachineKey | NodeKey | User  | IP addresses                  | Ephemeral | Last seen           | Expiration          | Connected | Expired
4  | laptop    | laptop    | [fLttA]    | [J2GVN] | alice | 100.64.0.2, fd7a:115c:a1e0::2 | false     | 2024-09-10 07:53:41 | 0001-01-01 00:00:00 | online    | no
5  | server    | laptop    | [BxUYW]    | [e4Bjc] | bob   | 100.64.0.3, fd7a:115c:a1e0::3 | false     | 2024-09-10 07:55:01 | 0001-01-01 00:00:00 | online    | no
```

### Environment

```markdown
- OS: Debian 12
- Headscale version: 0.23.0-beta.4
- Tailscale version: 1.72.1
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

_No response_

### LINKED ISSUE #2177: [Bug] Inconsistency ‘givenName’ in node
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Host name where the error occurs - `MacBook-Pro`
**(This is the real hostname of my machine)**

When registering a node on the network, `hostname` as well as `givenName` is stored in its original form from `tailcfg.Hostname` - `MacBook-Pro`, without making it based on FQDN rules.
When renaming a node (changing the `givenName`), the logic checks the new name for FQDN compliance (`CheckForFQDNRules`) and does not allow the `MacBook-Pro` name to be saved, requiring lowercase i.e. `macbook-pro`.

### Expected Behavior

When a node is registered on the network, the givenName is stored subject to FQDN rules.

### Steps To Reproduce

1. Register node
2. Show givenName in DB
3. Try changing the node name to the same
4. Receive an FQDN error
5. Save the new node name taking into account the FQDN rules
6. It's OK, the new name is saved

### Environment

```markdown
- OS: MacOS 15
- Headscale version: 0.22.3
- Tailscale version: 1.74.0
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

_No response_

### LINKED ISSUE #2343: [Bug] If a computer set an invalid hostname, the entire network will be unavailable
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a host is set with an invalid hostname (such as Chinese "我的电脑"), the entire network will become disconnected and new nodes is unable to connect.

### Expected Behavior

Similar to the official implementation of tailscale, rename the node to "node" (or add some random suffixes if the name is duplicated), and then successfully connect without affecting other nodes.

### Steps To Reproduce

1. Setup a invalid hostname (such as Chinese "我的电脑") on client
2. `tailscale up`
3. entire network become disconnected

### Environment

```markdown
- OS: Windows 11
- Headscale version: 0.23.0
- Tailscale version: 1.78.1
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

_No response_

### LINKED ISSUE #2449: [Bug] <title>Can't log in. Could not get the create map update error="tailNode, failed to create FQDN: failed to create valid FQDN: node has no given name"
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi, 
Today all my clients(windows, android, ios) can't log in to the headscale server.

Server displayed (`tail -f /var/log/syslog`)
```
Feb 25 12:28:20 ecm-f329 headscale[81449]: 2025-02-25T12:28:20+08:00 INF home/runner/work/headscale/headscale/hscontrol/poll.go:634 > node has connected, mapSession: 0xc0001cd200, chan: 0xc0000c2150 node=yks-hypc3 node.id=2857 omitPeers=false readOnly=false stream=true
Feb 25 12:28:20 ecm-f329 headscale[81449]: 2025-02-25T12:28:20+08:00 ERR home/runner/work/headscale/headscale/hscontrol/poll.go:654 > Could not get the create map update error="tailNode, failed to create FQDN: failed to create valid FQDN: node has no given name" node=yks-hypc3 node.id=2857 omitPeers=false readOnly=false stream=true
Feb 25 12:28:20 ecm-f329 headscale[81449]: 2025-02-25T12:28:20+08:00 INF home/runner/work/headscale/headscale/hscontrol/poll.go:634 > node has disconnected, mapSession: 0xc0001cd200, chan: 0xc0000c2150 node=yks-hypc3 node.id=2857 omitPeers=false readOnly=false stream=true
```
Image

Windows clients(version 1.80.0) displayed EOF or hanged forever when run 
```
tailscale up --accept-dns=false --accept-routes --force-reauth=true --login-server=http://host:ip --authkey=xxxx --unattended --hostname=myname
```
Image

Previously logged-in clients can still be used normally, but if they log out using `tailscale logout`, they will not be able to log in again using `tailscale up`.

Tsnet(version 1.78.3) applications displayed
```
2025/02/25 12:23:37 TsInternal control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2025/02/25 12:23:37 TsInternal control: [v1] No AuthURL
2025/02/25 12:23:37 TsInternal control: [v1] sendStatus: authRoutine-success: state:authenticated
2025/02/25 12:23:37 TsInternal control: [v1] restartMap: synced=false
2025/02/25 12:23:37 TsInternal control: [v1] authRoutine: state:authenticated; goal=nil paused=false
2025/02/25 12:23:37 TsInternal control: [v1] mapRoutine: context done.
2025/02/25 12:23:37 TsInternal control: [v1] mapRoutine: state:authenticated
2025/02/25 12:23:37 TsInternal [v1] authReconfig: netmap not yet valid. Skipping.
2025/02/25 12:23:37 TsInternal control: [v1] PollNetMap: stream=false ep=[]
2025/02/25 12:23:37 TsInternal control: [v1] PollNetMap: stream=true ep=[]
2025/02/25 12:23:37 TsInternal control: [v1] successful lite map update in 14ms
2025/02/25 12:23:37 TsInternal control: mapRoutine: [v1] backoff: 6 msec
2025/02/25 12:23:37 TsInternal control: [v1] PollNetMap: EOF
2025/02/25 12:23:37 TsInternal control: [v1] sendStatus: mapRoutine1: state:authenticated
2025/02/25 12:23:37 TsInternal control: [v1] mapRoutine: state:authenticated
2025/02/25 12:23:37 TsInternal control: [v1] PollNetMap: stream=true ep=[]
2025/02/25 12:23:37 TsInternal [v1] Received error: EOF
2025/02/25 12:23:37 TsInternal control: mapRoutine: [v1] backoff: 35 msec
2025/02/25 12:23:37 TsInternal control: [v1] PollNetMap: EOF
2025/02/25 12:23:37 TsInternal control: [v1] sendStatus: mapRoutine1: state:authenticated
2025/02/25 12:23:37 TsInternal control: [v1] mapRoutine: state:authenticated
2025/02/25 12:23:37 TsInternal control: [v1] PollNetMap: stream=true ep=[]
2025/02/25 12:23:37 TsInternal [v1] Received error: EOF
```

What's wrong? What should I do?

### Expected Behavior

Clients can log in.

### Steps To Reproduce

I didn't do anything. I just waited until today.

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- Headscale version: v0.24.0-beta.2.
- Tailscale version: 1.80.0, 1.78.3
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

_No response_

### LINKED ISSUE #2762: [Bug] If a computer set an invalid hostname, the entire network will be unavailable (re-emerging)
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have already learned that this issue was fixed in v0.25.0 #2343 #2393 , but it has reappeared in the current v0.26.1 version.

### Expected Behavior

Automatically replace node name with the correct string format.

### Steps To Reproduce

Just need to register a pure CJK character name Tailnet node on Headscale.

### Environment

```markdown
- OS: AlmaLinux 9
- Headscale version: v0.26.1
- Tailscale version: v1.86.2
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

Headscale Version:

Image

Error Logs:

Image

My Nodes:

Image

After I executed the following command, all nodes immediately returned to normal:

`podman exec -it headscale headscale nodes rename -i 8 abc`

### LINKED ISSUE #2926: [Bug] Normalization of hostnames
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

First off, love Headscale, it works great!

I think I found a bug in hostname handling.

When a client reports a hostname like "My-PC!", it fails ValidateHostname() and gets replaced with "invalid-xyz". Headscales code has a NormaliseHostname() function that would sanitize this to "my-pc".

The affected code paths are:
- ApplyHostnameFromHostInfo() *hscontrol/types/node.go*
- EnsureHostname() in *hscontrol/util/util.go*

Both use ValidateHostname() (reject if invalid), instead of NormaliseHostname() (sanitize and accept).

This seems like an oversight? The NormaliseHostname function exists but isn't being used.

### Expected Behavior

Expected: Hostname "My-PC!" → sanitized to "my-pc"
Actual: Hostname "My-PC!" → rejected, becomes "invalid-abc123"

### Steps To Reproduce

1. Register a node with hostname containing invalid characters:
### On client with hostname "My-PC!"
tailscale up --login-server https://your-headscale-server

2. List nodes on server:
headscale nodes list

3. Expected: Node appears as my-pc

4. Actual: Node appears as invalid-abc123

### Environment

```markdown
- Headscale version: v0.27.1
- Deployment: Docker
- OS: Ubuntu 24.04.3 LTS
- Docker: 29.0.2
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

This is a code logic issue, so dont believe debug log is useful.

### LINKED ISSUE #3188: [Bug] the server is not tolerant to the macos default naming
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

```
Apr 14 01:32:29 ip-172-31-12-195 headscale[78653]: 2026-04-14T01:32:29Z WRN Rejecting invalid hostname update from hostinfo error="hostname \"Yuri's macbook pro\" contains invalid characters, only lowercase letters, numbers, hyphens and dots are allowed" current_hostname=invalid-c8fqsf1w node.id=28 rejected_hostname="Yuri's MacBook Pro"
```

The rejected hostname issue is overwhelming, the default Apple's way of giving names to the device includes the `'` .

Can we resolve in the code with slight filtering of the current name?

### Expected Behavior

`'` is not a problem in the device reported name

### Steps To Reproduce

1. name the device with `'`
2. try connecting

### Environment

```markdown
- OS: linux x86 ubuntu 24.04
- Headscale version: 0.28.0
- Tailscale version: 1.96.5
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

N/A

### PR DESCRIPTION
**Pull request by kradalby**
Two disagreeing ingest paths, three duplicate regexes, and a
random-suffix collision fallback that drifted from Tailscale SaaS.
Apostrophes, spaces, dots, `@`, and non-ASCII were alternately
rejected or stored as `invalid-<rand>`. Same class of bug has shipped
six times since 2022.

Replace custom sanitiser with `tailscale.com/util/dnsname.SanitizeHostname`
and `ValidLabel`. Collision bumping moves inside `NodeStore.PutNode` /
`UpdateNode` — serialised through the single writer goroutine, so
concurrent registrations cannot duplicate. Admin rename uses the new
`SetGivenName`, which rejects collisions with `ErrGivenNameTaken`
rather than silently rewriting.

Empty-input fallback is now the literal `node`. MagicDNS names change
on upgrade for nodes previously stored with a random suffix; raw
`Hostname` is unchanged.

If `dnsname` drifts from SaaS later, the client has drifted too — fix
is a tailscale version bump, not new code here.

Fixes #3188
Fixes #2926
Fixes #2343
Fixes #2762
Fixes #2449
Fixes #2177
Fixes #2121
Fixes #363
Updates #2803
Closes #2976
Closes #3189
Closes #3195

> Generated with the help of an AI assistant

### CODE REVIEW

File: hscontrol/state/node_store.go [hunk 1]
```diff
@@ -12,13 +14,27 @@ import (
 	"github.com/prometheus/client_golang/prometheus/promauto"
 	"tailscale.com/types/key"
 	"tailscale.com/types/views"
+	"tailscale.com/util/dnsname"
+)
+
+// fallbackGivenName is the DNS label used when a node is written with
+// an empty GivenName. Matches Tailscale SaaS behaviour for empty
+// sanitised labels (see cmd/hostname-probe/testdata/SUMMARY.md).
```
Comment (kradalby) [inline hscontrol/state/node_store.go]: dont refer to this saas exercise or files not here.

File: hscontrol/state/node_store.go [hunk 2]
```diff
@@ -245,6 +264,49 @@ func (s *NodeStore) DeleteNode(id types.NodeID) {
...
+// Runs as a single writer-goroutine op, so the uniqueness check and
+// the write are atomic with respect to concurrent PutNode/UpdateNode.
+func (s *NodeStore) SetGivenName(id types.NodeID, label string) (types.NodeView, error) {
+	timer := prometheus.NewTimer(nodeStoreOperationDuration.WithLabelValues("set_name"))
+	defer timer.ObserveDuration()
+
+	w := work{
+		op:         setName,
+		nodeID:     id,
+		label:      label,
```
Comment (kradalby) [inline hscontrol/state/node_store.go]: label is wrong, its a hostname

File: hscontrol/state/node_store.go [hunk 3]
```diff
@@ -387,6 +500,63 @@ func (s *NodeStore) applyBatch(batch []work) {
...
+
+	return false
+}
+
+// isValidDNSLabel wraps dnsname.ValidLabel so callers inside the
+// writer goroutine can check pre-sanitised input without importing
+// the upstream package transitively.
+func isValidDNSLabel(label string) bool {
+	return dnsname.ValidLabel(label) == nil
+}
```
Comment (kradalby) [inline hscontrol/state/node_store.go]: this seems unnecessary

**Review by juanfont — APPROVED** [review]

**Comment by ykhrustalev** [comment]
are you guys going to cut a release soon on that?

**Comment by kradalby** [comment]
Not for this particular, it will go into 0.29.

I hope that we can start doing betas in less than a month.
